- name: install auditd
  apt:
    name: auditd
    state: present

- name: configure auditd
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
    owner: 'root'
    group: 'root'
    mode: '0640'
  notify:
    - reload auditd
    - enable auditd